// <auto-generated />
using System;
using CryptoTrackerApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoTrackerApi.Migrations
{
    [DbContext(typeof(CryptoDbContext))]
    [Migration("20260921130511_AddNetworkToEntity")]
    partial class AddNetworkToEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("CryptoTrackerApi.Domain.Entities.BlockchainData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BaseFee")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HighFee")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HighPriorityFee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastForkHash")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastForkHeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LatestUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LowFee")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LowPriorityFee")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MediumFee")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MediumPriorityFee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Network")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PeerCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviousHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UnconfirmedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name", "CreatedAt");

                    b.ToTable("BlockchainData", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
